# Generated by Django 5.2.3 on 2025-07-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailactivation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
