# Generated by Django 5.2.3 on 2025-07-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_all_users', 'Может просматривать всех пользователей'), ('block_user', 'Может блокировать пользователей')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
