# Generated by Django 5.2.3 on 2025-07-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('view_all_clients', 'Может просматривать всех клиентов'), ('block_client', 'Может блокировать клиентов')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('view_all_mailings', 'Может просматривать все рассылки'), ('toggle_mailing', 'Может включать/отключать рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылок'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('view_all_messages', 'Может просматривать все сообщения')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
